language: c
dist: trusty
sudo: false

branches:
  only:
  - master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - pkg-config openmpi-bin libopenmpi-dev gfortran zlib1g-dev

before_install:
  - test -n $CC && unset CC
  - test -n $FC && unset FC
  - test -n $CPPFLAGS && unset CPPFLAGS
  - test -n FCFLAGS && unset FCFLAGS

before_script:
  - export CC=mpicc
  - export FC=mpif90
  - export CPPFLAGS='-I/usr/include'
  - wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.4/src/hdf5-1.10.4.tar.gz
  - tar -xzvf hdf5-1.10.4.tar.gz
  - pushd hdf5-1.10.4
  - ./configure --prefix=/usr --enable-parallel
  - make
  - sudo make install
  - popd
  - wget https://github.com/Unidata/netcdf-c/archive/v4.6.3.tar.gz
  - tar -xzvf v4.6.3.tar.gz
  - pushd netcdf-c-4.6.3
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - popd
  - wget https://parallel-netcdf.github.io/Release/pnetcdf-1.11.0.tar.gz 
  - tar -xzvf pnetcdf-1.11.0.tar.gz
  - pushd pnetcdf-1.11.0
  - ./configure --prefix=/usr --enable-shared
  - make 
  - sudo make install
  - popd
env:
  global:
    - CC=mpicc
    - FC=mpif90
    - CPPFLAGS='-I/usr/include'
    - CFLAGS='-std=c99'
    - LDFLAGS='-L/usr/lib'
  
script:
  - autoreconf -i
  - ./configure
  - make -j distcheck
  - rm -rf build
  - mkdir build
  - cd build
  - cmake -DPIO_HDF5_LOGGING=On -DPIO_USE_MALLOC=On -DPIO_ENABLE_LOGGING=On -DPIO_ENABLE_TIMING=Off ..
  - make VERBOSE=1
  - make tests VERBOSE=1
  - make test VERBOSE=1
  
 
