name: netcdf-4.7.4_pnetcdf-12.1_ncint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CPPFLAGS: "-I/home/runner/openmpi/include -I/home/runner/hdf5/include -I/home/runner/netcdf-c/include -I/home/runner/netcdf-fortran/include -I/home/runner/pnetcdf/include"
      LDFLAGS: "-L/home/runner/openmpi/lib -L/home/runner/hdf5/lib -L/home/runner/netcdf-c/lib -L/home/runner/netcdf-fortran/lib -L/home/runner/pnetcdf/lib"

    steps:
    - uses: actions/checkout@v2
    - name: Installs
      run: |
        sudo apt-get install doxygen graphviz wget gfortran libjpeg-dev libz-dev
    - name: cache-openmpi
      id: cache-openmpi
      uses: actions/cache@v2
      with:
        path: ~/openmpi
        key: openmpi-${{ runner.os }}-4.0.4

    - name: build-openmpi
      if: steps.cache-openmpi.outputs.cache-hit != 'true'
      run: |
        wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.4.tar.gz &> /dev/null
        tar -xzf openmpi-4.0.4.tar.gz
        pushd openmpi-4.0.4
        ./configure --prefix=/home/runner/openmpi
        make
        sudo make install
        popd
    - name: cache-hdf5
      id: cache-hdf5
      uses: actions/cache@v2
      with:
        path: ~/hdf5
        key: hdf5-${{ runner.os }}-1.10.6

    - name: build-hdf5
      if: steps.cache-hdf5.outputs.cache-hit != 'true'
      run: |
        set -x
        ls -l /home/runner/openmpi/bin
        export PATH="/home/runner/openmpi/bin:$PATH"
        echo $PATH
        export CC=/home/runner/openmpi/mpicc
        wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.6/src/hdf5-1.10.6.tar.gz &> /dev/null
        tar -xzf hdf5-1.10.6.tar.gz
        pushd hdf5-1.10.6
        ./configure --prefix=/home/runner/hdf5 --enable-parallel --disable-tools --disable-fortran --disable-cxx
        make
        sudo make install
        popd
    - name: autoreconf
      run: autoreconf -i
