name: netcdf-4.7.4_pnetcdf-12.1_ncint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CPPFLAGS: "-I/home/runner/hdf5/include -I/home/runner/netcdf-c/include -I/home/runner/netcdf-fortran/include -I/home/runner/pnetcdf/include"
      LDFLAGS: "-L/home/runner/hdf5/lib -L/home/runner/netcdf-c/lib -L/home/runner/netcdf-fortran/lib -L/home/runner/pnetcdf/lib"

    steps:
    - uses: actions/checkout@v2
    - name: Installs
      run: |
        sudo apt-get install doxygen graphviz wget gfortran libjpeg-dev libz-dev
    - name: cache-openmpi
      id: cache-openmpi
      uses: actions/cache@v2
      with:
        path: ~/openmpi
        key: openmpi-${{ runner.os }}-4.0.4

    - name: build-openmpi
      if: steps.cache-openmpi.outputs.cache-hit != 'true'
      run: |
        wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.4.tar.gz &> /dev/null
        tar -xzf openmpi-4.0.4.tar.gz
        pushd openmpi-4.0.4
        ./configure --prefix=/home/runner/openmpi
        make
        sudo make install
        popd
    - name: autoreconf
      run: autoreconf -i
